/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-07-11 14:14:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_002dsupplier_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	if (session == null || session.getAttribute("sessionId") == null || session.getAttribute("admin") == null) {
		request.setAttribute("errorAccess", "Session expired or user not logged in. Please log in again.");
	    response.sendRedirect("login.jsp");
	}
	
	// Prevent caching
	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1.
	response.setHeader("Pragma", "no-cache"); // HTTP 1.0.
	response.setDateHeader("Expires", 0); // Proxies.

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("      <title>Add Supplier | redeemMe</title>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Favicon -->\r\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/backend-plugin.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/backend.css?v=1.0.0\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/@fortawesome/fontawesome-free/css/all.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/remixicon/fonts/remixicon.css\">  </head>\r\n");
      out.write("\r\n");
      out.write("      <!-- css -->\r\n");
      out.write("      <style>\r\n");
      out.write("        .las.la-bars.wrapper-menu:hover, .ri-menu-line.wrapper-menu:hover {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.border.sign-out{\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: medium;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.border.sign-out:hover{\r\n");
      out.write("            background-color: #e32323;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            transition: all 0.7s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("      </style>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"  \">\r\n");
      out.write("    <!-- loader Start -->\r\n");
      out.write("    <div id=\"loading\">\r\n");
      out.write("          <div id=\"loading-center\">\r\n");
      out.write("          </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- loader END -->\r\n");
      out.write("    <!-- Wrapper Start -->\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"iq-sidebar  sidebar-default \">\r\n");
      out.write("          <div class=\"iq-sidebar-logo d-flex align-items-center justify-content-between\">\r\n");
      out.write("              <a href=\"ViewDashboard\" class=\"header-logo\">\r\n");
      out.write("                  <img src=\"assets/images/logo.png\" class=\"img-fluid rounded-normal light-logo\" alt=\"logo\"><h5 class=\"logo-title light-logo ml-3\">redeemMe</h5>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"iq-menu-bt-sidebar ml-0\">\r\n");
      out.write("                  <i class=\"las la-bars wrapper-menu\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"data-scrollbar\" data-scroll=\"1\">\r\n");
      out.write("              <nav class=\"iq-sidebar-menu\">\r\n");
      out.write("                  <ul id=\"iq-sidebar-toggle\" class=\"iq-menu\">\r\n");
      out.write("                      <li class=\" \">\r\n");
      out.write("                          <a href=\"ViewDashboard\" class=\"svg-icon\">                        \r\n");
      out.write("                              <svg  class=\"svg-icon\" id=\"p-dash1\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                  <path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path><polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"></polyline><line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                              <span class=\"ml-4\">Dashboards</span>\r\n");
      out.write("                          </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\" \">\r\n");
      out.write("                          <a href=\"#product\" class=\"collapsed\" data-toggle=\"collapse\" aria-expanded=\"false\">\r\n");
      out.write("                            <svg class=\"svg-icon\" id=\"p-dash3\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"9\" y=\"9\" width=\"13\" height=\"13\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                <path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"></path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                              <span class=\"ml-4\">Products</span>\r\n");
      out.write("                              <svg class=\"svg-icon iq-arrow-right arrow-active\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                  <polyline points=\"10 15 15 20 20 15\"></polyline><path d=\"M4 4h7a4 4 0 0 1 4 4v12\"></path>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                          </a>\r\n");
      out.write("                          <ul id=\"product\" class=\"iq-submenu collapse\" data-parent=\"#iq-sidebar-toggle\">\r\n");
      out.write("                              <li class=\"\">\r\n");
      out.write("                                  <a href=\"ListProductController\">\r\n");
      out.write("                                      <i class=\"las la-minus\"></i><span>List Product</span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"\">\r\n");
      out.write("                                  <a href=\"ViewSupplierNameController\">\r\n");
      out.write("                                      <i class=\"las la-minus\"></i><span>Add Product</span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\" \">\r\n");
      out.write("                          <a href=\"#return\" class=\"collapsed\" data-toggle=\"collapse\" aria-expanded=\"false\">\r\n");
      out.write("                              <svg class=\"svg-icon\" id=\"p-dash6\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                  <polyline points=\"4 14 10 14 10 20\"></polyline><polyline points=\"20 10 14 10 14 4\"></polyline><line x1=\"14\" y1=\"10\" x2=\"21\" y2=\"3\"></line><line x1=\"3\" y1=\"21\" x2=\"10\" y2=\"14\"></line>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                              <span class=\"ml-4\">Suppliers</span>\r\n");
      out.write("                              <svg class=\"svg-icon iq-arrow-right arrow-active\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                  <polyline points=\"10 15 15 20 20 15\"></polyline><path d=\"M4 4h7a4 4 0 0 1 4 4v12\"></path>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                          </a>\r\n");
      out.write("                          <ul id=\"return\" class=\"iq-submenu collapse\" data-parent=\"#iq-sidebar-toggle\">\r\n");
      out.write("                                  <li class=\"\">\r\n");
      out.write("                                          <a href=\"ListSupplierController\">\r\n");
      out.write("                                              <i class=\"las la-minus\"></i><span>List Supplier</span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li class=\"active\">\r\n");
      out.write("                                          <a href=\"admin-supplier-add.jsp\">\r\n");
      out.write("                                              <i class=\"las la-minus\"></i><span>Add Supplier</span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\" \">\r\n");
      out.write("                          <a href=\"ListUserController\">\r\n");
      out.write("                              <svg class=\"svg-icon\" id=\"p-dash8\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                  <path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path><circle cx=\"9\" cy=\"7\" r=\"4\"></circle><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                              <span class=\"ml-4\">Customers</span>\r\n");
      out.write("                          </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\" \">\r\n");
      out.write("                        <a href=\"ListOrderController\">\r\n");
      out.write("                            <svg class=\"svg-icon\" id=\"p-dash5\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"1\" y=\"4\" width=\"22\" height=\"16\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                <line x1=\"1\" y1=\"10\" x2=\"23\" y2=\"10\"></line>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            <span class=\"ml-4\">Orders</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\" \">\r\n");
      out.write("                        <a href=\"register-admin.jsp\">\r\n");
      out.write("                            <svg class=\"svg-icon\" id=\"p-dash5\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"1\" y=\"4\" width=\"22\" height=\"16\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                <line x1=\"1\" y1=\"20\" x2=\"23\" y2=\"20\"></line>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            <span class=\"ml-4\">Register Admin</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("              </nav>\r\n");
      out.write("              <div id=\"sidebar-bottom\" class=\"position-relative sidebar-bottom\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>      <div class=\"iq-top-navbar\">\r\n");
      out.write("          <div class=\"iq-navbar-custom\">\r\n");
      out.write("              <nav class=\"navbar navbar-expand-lg navbar-light p-0\">\r\n");
      out.write("                  <div class=\"iq-navbar-logo d-flex align-items-center justify-content-between\">\r\n");
      out.write("                      <i class=\"ri-menu-line wrapper-menu\"></i>\r\n");
      out.write("                      <a href=\"ViewDashboard\" class=\"header-logo\">\r\n");
      out.write("                          <img src=\"assets/images/logo.png\" class=\"img-fluid rounded-normal\" alt=\"logo\">\r\n");
      out.write("                          <h5 class=\"logo-title ml-3\">redeemMe</h5>\r\n");
      out.write("                      </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("                      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("                          data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("                          aria-label=\"Toggle navigation\">\r\n");
      out.write("                          <i class=\"ri-menu-3-line\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                          <ul class=\"navbar-nav ml-auto navbar-list align-items-center\">\r\n");
      out.write("                              <li class=\"nav-item nav-icon dropdown\" style=\"display: flex; align-self: end;\">\r\n");
      out.write("                                  <p>Hi, <span style=\"color: red;\">ADMIN</span></p>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item nav-icon dropdown caption-content\">\r\n");
      out.write("                                  <a href=\"#\" class=\"search-toggle dropdown-toggle\" id=\"dropdownMenuButton4\"\r\n");
      out.write("                                      data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                      <img src=\"assets/images/user/1.png\" class=\"img-fluid rounded\" alt=\"user\">\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <div class=\"iq-sub-dropdown dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                                      <div class=\"card shadow-none m-0\">\r\n");
      out.write("                                          <div class=\"card-body p-0 text-center\">\r\n");
      out.write("                                              <div class=\"media-body profile-detail text-center\">\r\n");
      out.write("                                                  <img src=\"assets/images/page-img/profile-bg.jpg\" alt=\"profile-bg\"\r\n");
      out.write("                                                      class=\"rounded-top img-fluid mb-4\">\r\n");
      out.write("                                                  <img src=\"assets/images/user/1.png\" alt=\"profile-img\"\r\n");
      out.write("                                                      class=\"rounded profile-img img-fluid avatar-70\">\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"p-3\">\r\n");
      out.write("                                                  <p class=\"mb-0\">ADMIN</p>\r\n");
      out.write("                                                  <div class=\"d-flex align-items-center justify-content-center mt-3\">\r\n");
      out.write("                                                      <a href=\"login.jsp\" class=\"btn border sign-out\">Sign Out</a>\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>    <div class=\"content-page\">\r\n");
      out.write("        <div class=\"container-fluid add-form-list\">\r\n");
      out.write("           <div class=\"row\">\r\n");
      out.write("               <div class=\"col-sm-12\">\r\n");
      out.write("                   <div class=\"card\">\r\n");
      out.write("                       <div class=\"card-header d-flex justify-content-between\">\r\n");
      out.write("                           <div class=\"header-title\">\r\n");
      out.write("                               <h4 class=\"card-title\">Add Supplier</h4>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"card-body\">\r\n");
      out.write("                           <form action=\"AddSupplierController\" method=\"post\">\r\n");
      out.write("                               <div class=\"row\">\r\n");
      out.write("                                   <div class=\"col-md-12\">\r\n");
      out.write("                                       <div class=\"form-group\">\r\n");
      out.write("                                           <label>Name *</label>\r\n");
      out.write("                                           <input type=\"text\" name=\"SupplierName\" class=\"form-control\" placeholder=\"Enter Supplier Name\" required pattern=\"[A-Za-z ]+\" title=\"Please enter a valid name\">\r\n");
      out.write("                                       </div> \r\n");
      out.write("                                   </div>  \r\n");
      out.write("                                   <div class=\"col-md-6\">                      \r\n");
      out.write("                                       <div class=\"form-group\">\r\n");
      out.write("                                           <label>Phone Number *</label>\r\n");
      out.write("                                           <input type=\"text\" name=\"SupplierNum\" class=\"form-control\" placeholder=\"Enter Supplier Contact\" required pattern=\"0\\d{8,10}\" maxlength=\"11\" title=\"Please enter a valid phone number starting with 0 and contains 9-11 digits\">\r\n");
      out.write("                                       </div>\r\n");
      out.write("                                   </div>    \r\n");
      out.write("                                   <div class=\"col-md-6\">\r\n");
      out.write("                                       <div class=\"form-group\">\r\n");
      out.write("                                           <label>Email *</label>\r\n");
      out.write("                                           <input type=\"email\" name=\"SupplierEmail\" class=\"form-control\" placeholder=\"Enter Supplier Email\" required pattern=\".+\\.com$\" title=\"Please enter a valid email ending with .com\">\r\n");
      out.write("                                       </div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label>Address 1 *</label>\r\n");
      out.write("                                            <input type=\"text\" name=\"SupplierAdd1\" class=\"form-control\" placeholder=\"Enter Supplier Address 1\" required>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label>Address 2 *</label>\r\n");
      out.write("                                            <input type=\"text\" name=\"SupplierAdd2\" class=\"form-control\" placeholder=\"Enter Supplier Address 2\" required>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label>Postcode *</label>\r\n");
      out.write("                                            <input type=\"text\" name=\"SupplierPostcode\" class=\"form-control\" placeholder=\"Enter Supplier Postcode\" required pattern=\"\\d{5}\" maxlength=\"5\" title=\"Please enter a valid postcode that contains exactly 5 digits\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label>City *</label>\r\n");
      out.write("                                            <input type=\"text\" name=\"SupplierCity\" class=\"form-control\" placeholder=\"Enter Supplier City\" required pattern=\"[A-Za-z ]+\" title=\"Please enter a valid city\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                   <div class=\"col-md-12\">\r\n");
      out.write("                                       <div class=\"form-group\">\r\n");
      out.write("                                           <label for=\"state\">State *</label>\r\n");
      out.write("                                            <select id=\"state\" name=\"SupplierState\" class=\"form-control\" required>\r\n");
      out.write("                                                <option disabled selected value=\"\">Select Supplier State</option>\r\n");
      out.write("                                                <option value=\"Johor\">Johor</option>\r\n");
      out.write("                                                <option value=\"Kedah\">Kedah</option>\r\n");
      out.write("                                                <option value=\"Kelantan\">Kelantan</option>\r\n");
      out.write("                                                <option value=\"Melaka\">Melaka</option>\r\n");
      out.write("                                                <option value=\"Negeri Sembilan\">Negeri Sembilan</option>\r\n");
      out.write("                                                <option value=\"Pahang\">Pahang</option>\r\n");
      out.write("                                                <option value=\"Perak\">Perak</option>\r\n");
      out.write("                                                <option value=\"Perlis\">Perlis</option>\r\n");
      out.write("                                                <option value=\"Pulau Pinang\">Pulau Pinang</option>\r\n");
      out.write("                                                <option value=\"Sabah\">Sabah</option>\r\n");
      out.write("                                                <option value=\"Sarawak\">Sarawak</option>\r\n");
      out.write("                                                <option value=\"Selangor\">Selangor</option>\r\n");
      out.write("                                                <option value=\"Terengganu\">Terengganu</option>\r\n");
      out.write("                                                <option value=\"Wilayah Persekutuan Kuala Lumpur\">Wilayah Persekutuan Kuala Lumpur</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                   </div>\r\n");
      out.write("                               </div>                            \r\n");
      out.write("                               <button type=\"submit\" class=\"btn btn-primary mr-2\">Add Supplier</button>\r\n");
      out.write("                               <button type=\"reset\" class=\"btn btn-danger\">Reset</button>\r\n");
      out.write("                           </form>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("           <!-- Page end  -->\r\n");
      out.write("       </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     \r\n");
      out.write("        <!-- Page end  -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper End-->\r\n");
      out.write("    <footer class=\"iq-footer\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-body\" style=\"text-align: center;\">\r\n");
      out.write("                    <span class=\"mr-1\"><script>document.write(new Date().getFullYear())</script>©</span> <a href=\"ViewDashboard\" class=\"\">redeemMe</a>.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("  	");

        String emptyFieldSupplier = (String) request.getAttribute("emptyFieldSupplier");
        if (emptyFieldSupplier != null) {
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print( emptyFieldSupplier );
      out.write("');\r\n");
      out.write("    </script>\r\n");
      out.write("    ");

        // Remove the attribute to prevent it from appearing again on page refresh
        request.removeAttribute("emptyFieldSupplier");
    }
	
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Backend Bundle JavaScript -->\r\n");
      out.write("    <script src=\"assets/js/backend-bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Table Treeview JavaScript -->\r\n");
      out.write("    <script src=\"assets/js/table-treeview.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Chart Custom JavaScript -->\r\n");
      out.write("    <script src=\"assets/js/customizer.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Chart Custom JavaScript -->\r\n");
      out.write("    <script async src=\"assets/js/chart-custom.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- app JavaScript -->\r\n");
      out.write("    <script src=\"assets/js/app.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
