/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-07-08 17:47:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1719740462921L));
    _jspx_dependants.put("jar:file:/C:/Users/aqima/OneDrive/Desktop/myproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/RedeemMe/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602845172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");


  // Invalidate the session
  session.invalidate();
  
  // Set Cache-Control header to instruct browsers and intermediate caches not to cache the response
  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  
  // Set Pragma header to prevent caching in older browsers
  response.setHeader("Pragma", "no-cache");
  
  // Set Expires header to ensure that the response is not cached by proxies or the client's browser
  response.setDateHeader("Expires", 0);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Login</title>\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/login.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("    <header>Login Form</header>\r\n");
      out.write("    <form action=\"LoginController\" method=\"POST\">\r\n");
      out.write("      <div class=\"field email\">\r\n");
      out.write("        <div class=\"input-area\">\r\n");
      out.write("          <input type=\"text\" name=\"email\" placeholder=\"Email Address\" required>\r\n");
      out.write("          <i class=\"icon fas fa-envelope\"></i>\r\n");
      out.write("          <i class=\"error error-icon fas fa-exclamation-circle\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"error error-txt\">Email can't be blank</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"field password\">\r\n");
      out.write("        <div class=\"input-area\">\r\n");
      out.write("          <input type=\"password\" name=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("          <i class=\"icon fas fa-lock\"></i>\r\n");
      out.write("          <i class=\"error error-icon fas fa-exclamation-circle\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"error error-txt\">Password can't be blank</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <input type=\"submit\" value=\"Login\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <div class=\"sign-txt\">Don't have an account? <a href=\"sign-up.jsp\">Signup now</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  	");

        String error = (String) request.getAttribute("error");
        if (error != null) {
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print( error );
      out.write("');\r\n");
      out.write("    </script>\r\n");
      out.write("    ");

        // Remove the attribute to prevent it from appearing again on page refresh
        request.removeAttribute("error");
    }
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

        String successful = (String) request.getAttribute("successful");
        if (successful != null) {
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print( successful );
      out.write("');\r\n");
      out.write("    </script>\r\n");
      out.write("	");

        // Remove the attribute to prevent it from appearing again on page refresh
        request.removeAttribute("successful");
    }
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    ");

        String errorAccess = (String) request.getAttribute("errorAccess");
        if (errorAccess != null) {
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print( errorAccess );
      out.write("');\r\n");
      out.write("    </script>\r\n");
      out.write("	");

        // Remove the attribute to prevent it from appearing again on page refresh
        request.removeAttribute("errorAccess");
    }
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
