/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-07-11 13:27:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class sign_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1719740462921L));
    _jspx_dependants.put("jar:file:/C:/Users/aqima/OneDrive/Desktop/myproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/RedeemMe/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602845172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Prevent caching
    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1.
    response.setHeader("Pragma", "no-cache"); // HTTP 1.0.
    response.setDateHeader("Expires", 0); // Proxies.


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <!----======== CSS ======== -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/sign-up.css\">\r\n");
      out.write("     \r\n");
      out.write("    <!----===== Iconscout CSS ===== -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unicons.iconscout.com/release/v4.0.0/css/line.css\">\r\n");
      out.write("\r\n");
      out.write("   <title>Registration Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <span>Registration</span>\r\n");
      out.write("            <span class=\"goto-login\">Already have account? <a href=\"login.jsp\">log in</a></span>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"myForm\" action=\"AddUserController\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <div class=\"form first\">\r\n");
      out.write("                <div class=\"details personal\">\r\n");
      out.write("                    <span class=\"title\">Personal Details</span>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"fields\">\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>First Name</label>\r\n");
      out.write("                            <input type=\"text\" name=\"first-name\" placeholder=\"Enter your first name\" required pattern=\"[A-Za-z ]+\" title=\"Please enter a valid name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Last Name</label>\r\n");
      out.write("                            <input type=\"text\" name=\"last-name\" placeholder=\"Enter your last name\" required pattern=\"[A-Za-z ]+\" title=\"Please enter a valid name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Email</label>\r\n");
      out.write("                            <input type=\"email\" name=\"email\" placeholder=\"Enter your email\" required pattern=\".+\\.com$\" title=\"Please enter a valid email ending with .com\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Password</label>\r\n");
      out.write("                            <input type=\"password\" name=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Mobile Number</label>\r\n");
      out.write("                            <input type=\"text\" name=\"contact\" placeholder=\"Enter your mobile number\" required pattern=\"01\\d{8,9}\" maxlength=\"11\" title=\"Please enter a valid phone number starting with 01 and contains 10-11 digits\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Profile picture (optional)</label>\r\n");
      out.write("                            <input type=\"file\" id=\"image\" name=\"image\" accept=\"image/jpeg, image/png\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"details ID\">\r\n");
      out.write("                    <span class=\"title\">Identity Details</span>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"fields\">\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Address 1</label>\r\n");
      out.write("                            <input type=\"text\" name=\"address1\" placeholder=\"Enter your first address\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Address 2</label>\r\n");
      out.write("                            <input type=\"text\" name=\"address2\" placeholder=\"Enter your second address\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>Postcode</label>\r\n");
      out.write("                            <input type=\"text\" name=\"postcode\" placeholder=\"Enter your postcode\" required pattern=\"\\d{5}\" maxlength=\"5\" title=\"Please enter a valid postcode that contains exactly 5 digits\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label>City</label>\r\n");
      out.write("                            <input type=\"text\" name=\"city\" placeholder=\"Enter your city\" required pattern=\"[A-Za-z ]+\" title=\"Please enter a valid city\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <label for=\"state\">State</label>\r\n");
      out.write("                            <select id=\"state\" name=\"state\" required>\r\n");
      out.write("                                <option disabled selected value=\"\">Select state</option>\r\n");
      out.write("                                <option value=\"Johor\">Johor</option>\r\n");
      out.write("                                <option value=\"Kedah\">Kedah</option>\r\n");
      out.write("                                <option value=\"Kelantan\">Kelantan</option>\r\n");
      out.write("                                <option value=\"Melaka\">Melaka</option>\r\n");
      out.write("                                <option value=\"Negeri Sembilan\">Negeri Sembilan</option>\r\n");
      out.write("                                <option value=\"Pahang\">Pahang</option>\r\n");
      out.write("                                <option value=\"Perak\">Perak</option>\r\n");
      out.write("                                <option value=\"Perlis\">Perlis</option>\r\n");
      out.write("                                <option value=\"Pulau Pinang\">Pulau Pinang</option>\r\n");
      out.write("                                <option value=\"Sabah\">Sabah</option>\r\n");
      out.write("                                <option value=\"Sarawak\">Sarawak</option>\r\n");
      out.write("                                <option value=\"Selangor\">Selangor</option>\r\n");
      out.write("                                <option value=\"Terengganu\">Terengganu</option>\r\n");
      out.write("                                <option value=\"Wilayah Persekutuan Kuala Lumpur\">Wilayah Persekutuan Kuala Lumpur</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button class=\"nextBtn\" type=\"submit\">\r\n");
      out.write("                        Submit\r\n");
      out.write("                        <i class=\"uil uil-navigator\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    \r\n");
      out.write("                </div> \r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");

    String sqlError = (String) request.getAttribute("sqlError");
    if (sqlError != null) {

      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print( sqlError );
      out.write("');\r\n");
      out.write("    </script>\r\n");

        // Remove the attribute to prevent it from appearing again on page refresh
        request.removeAttribute("sqlError");
    }

      out.write("\r\n");
      out.write("\r\n");

    String emptyField = (String) request.getAttribute("emptyField");
    if (emptyField != null) {

      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print( emptyField );
      out.write("');\r\n");
      out.write("    </script>\r\n");

        // Remove the attribute to prevent it from appearing again on page refresh
        request.removeAttribute("emptyField");
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
