/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-06-30 10:19:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class customer_002dreceipt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("      <title>redeemMe</title>\n");
      out.write("      \n");
      out.write("      <!-- Favicon -->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/backend-plugin.min.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/backend.css?v=1.0.0\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/@fortawesome/fontawesome-free/css/all.min.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/remixicon/fonts/remixicon.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/customer-receipt.css\">  \n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("      <!-- css -->\n");
      out.write("      <style>\n");
      out.write("        .las.la-bars.wrapper-menu:hover, .ri-menu-line.wrapper-menu:hover {\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn.border.sign-out{\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: medium;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn.border.sign-out:hover{\n");
      out.write("            background-color: #e32323;\n");
      out.write("            color: #ffffff;\n");
      out.write("            transition: all 0.7s ease-in-out;\n");
      out.write("        }\n");
      out.write("      </style>\n");
      out.write("\n");
      out.write("  <body class=\"  \">\n");
      out.write("    <!-- loader Start -->\n");
      out.write("    <div id=\"loading\">\n");
      out.write("          <div id=\"loading-center\">\n");
      out.write("          </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- loader END -->\n");
      out.write("    <!-- Wrapper Start -->\n");
      out.write("    <div class=\"wrapper\">\n");
      out.write("      \n");
      out.write("      <div class=\"iq-sidebar  sidebar-default \">\n");
      out.write("          <div class=\"iq-sidebar-logo d-flex align-items-center justify-content-between\">\n");
      out.write("              <a href=\"customer-shop.jsp\" class=\"header-logo\">\n");
      out.write("                  <img src=\"assets/images/logo.png\" class=\"img-fluid rounded-normal light-logo\" alt=\"logo\"><h5 class=\"logo-title light-logo ml-3\">redeemMe</h5>\n");
      out.write("              </a>\n");
      out.write("              <div class=\"iq-menu-bt-sidebar ml-0\">\n");
      out.write("                  <i class=\"las la-bars wrapper-menu\"></i>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"data-scrollbar\" data-scroll=\"1\">\n");
      out.write("            <nav class=\"iq-sidebar-menu\">\n");
      out.write("                <ul id=\"iq-sidebar-toggle\" class=\"iq-menu\">\n");
      out.write("                    <li class=\"active\">\n");
      out.write("                        <a href=\"customer-profile.jsp\" class=\"svg-icon\">                        \n");
      out.write("                          <svg class=\"svg-icon\" id=\"p-dash8\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n");
      out.write("                              <path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path><circle cx=\"9\" cy=\"7\" r=\"4\"></circle><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path>\n");
      out.write("                          </svg>\n");
      out.write("                            <span class=\"ml-4\">Profile</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\" \">\n");
      out.write("                        <a href=\"ListProductControllerCustomer\">\n");
      out.write("                          <svg class=\"svg-icon\" id=\"p-dash2\" width=\"20\" height=\"20\"  xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"9\" cy=\"21\" r=\"1\"></circle><circle cx=\"20\" cy=\"21\" r=\"1\"></circle>\n");
      out.write("                              <path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path>\n");
      out.write("                          </svg>\n");
      out.write("                            <span class=\"ml-4\">Shop</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\" \">\n");
      out.write("                      <a href=\"customer-purchases.jsp\">\n");
      out.write("                          <svg class=\"svg-icon\" id=\"p-dash5\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"1\" y=\"4\" width=\"22\" height=\"16\" rx=\"2\" ry=\"2\"></rect>\n");
      out.write("                              <line x1=\"1\" y1=\"10\" x2=\"23\" y2=\"10\"></line>\n");
      out.write("                          </svg>\n");
      out.write("                          <span class=\"ml-4\">Purchases</span>\n");
      out.write("                      </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("            <div id=\"sidebar-bottom\" class=\"position-relative sidebar-bottom\"></div>\n");
      out.write("        </div>\n");
      out.write("          </div>      <div class=\"iq-top-navbar\">\n");
      out.write("          <div class=\"iq-navbar-custom\">\n");
      out.write("              <nav class=\"navbar navbar-expand-lg navbar-light p-0\">\n");
      out.write("                  <div class=\"iq-navbar-logo d-flex align-items-center justify-content-between\">\n");
      out.write("                      <i class=\"ri-menu-line wrapper-menu\"></i>\n");
      out.write("                      <a href=\"customer-shop.jsp\" class=\"header-logo\">\n");
      out.write("                          <img src=\"assets/images/logo.png\" class=\"img-fluid rounded-normal\" alt=\"logo\">\n");
      out.write("                          <h5 class=\"logo-title ml-3\">redeemMe</h5>\n");
      out.write("                      </a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"current-points\">\n");
      out.write("                    Your Points: <c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.points}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> &#9733;\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"d-flex align-items-center\">\n");
      out.write("                      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("                          data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\n");
      out.write("                          aria-label=\"Toggle navigation\">\n");
      out.write("                          <i class=\"ri-menu-3-line\"></i>\n");
      out.write("                      </button>\n");
      out.write("                      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                          <ul class=\"navbar-nav ml-auto navbar-list align-items-center\">\n");
      out.write("                              <li class=\"nav-item nav-icon dropdown\" style=\"display: flex; align-self: end;\">\n");
      out.write("                                  <p>Hi, <span style=\"color: red;\">user</span></p>\n");
      out.write("                              </li>\n");
      out.write("                              <li class=\"nav-item nav-icon dropdown caption-content\">\n");
      out.write("                                  <a href=\"#\" class=\"search-toggle dropdown-toggle\" id=\"dropdownMenuButton4\"\n");
      out.write("                                      data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                      <img src=\"assets/images/user/1.png\" class=\"img-fluid rounded\" alt=\"user\">\n");
      out.write("                                  </a>\n");
      out.write("                                  <div class=\"iq-sub-dropdown dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\n");
      out.write("                                      <div class=\"card shadow-none m-0\">\n");
      out.write("                                          <div class=\"card-body p-0 text-center\">\n");
      out.write("                                              <div class=\"media-body profile-detail text-center\">\n");
      out.write("                                                  <img src=\"assets/images/page-img/profile-bg.jpg\" alt=\"profile-bg\"\n");
      out.write("                                                      class=\"rounded-top img-fluid mb-4\">\n");
      out.write("                                                  <img src=\"assets/images/user/1.png\" alt=\"profile-img\"\n");
      out.write("                                                      class=\"rounded profile-img img-fluid avatar-70\">\n");
      out.write("                                              </div>\n");
      out.write("                                              <div class=\"p-3\">\n");
      out.write("                                                  <p class=\"mb-0\">customer email</p>\n");
      out.write("                                                  <div class=\"d-flex align-items-center justify-content-center mt-3\">\n");
      out.write("                                                      <a href=\"login.jsp\" class=\"btn border sign-out\">Sign Out</a>\n");
      out.write("                                                  </div>\n");
      out.write("                                              </div>\n");
      out.write("                                          </div>\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                              </li>\n");
      out.write("                          </ul>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("              </nav>\n");
      out.write("          </div>\n");
      out.write("      </div>    <div class=\"content-page\">\n");
      out.write("<!-- Starts here -->\n");
      out.write("<div class=\"container-fluid my-5  d-flex  justify-content-center\">\n");
      out.write("    <div class=\"card card-1\">\n");
      out.write("        <div class=\"card-header bg-white\">\n");
      out.write("            <div class=\"media flex-sm-row flex-column-reverse justify-content-between  \">\n");
      out.write("                <div class=\"col my-auto\"> <h4 class=\"mb-0\">Thanks for your Order,<span class=\"change-color\"><c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lastName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></span> !</h4> </div>\n");
      out.write("                <div class=\"col-auto text-center  my-auto pl-0 pt-sm-4\"> <img class=\"img-fluid my-auto align-items-center mb-0 pt-3\"  src=\"assets/images/favicon.ico\" width=\"115\" height=\"115\"> <p class=\"mb-4 pt-0 Glasses\">Your Happiness is Our Service</p>  </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <div class=\"row justify-content-between mb-3\">\n");
      out.write("                <div class=\"col-auto\"> <h6 class=\"color-1 mb-0 change-color\">Receipt</h6> </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col\">\n");
      out.write("                    <div class=\"card card-2\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <div class=\"media\">\n");
      out.write("                                <div class=\"sq align-self-center \"> <img class=\"img-fluid  my-auto align-self-center mr-2 mr-md-4 pl-0 p-0 m-0\" src=\"assets/images/Spectacles.jpeg\" width=\"135\" height=\"135\" /> </div>\n");
      out.write("                                <div class=\"media-body my-auto text-right\">\n");
      out.write("                                    <div class=\"row  my-auto flex-column flex-md-row\">\n");
      out.write("                                        <div class=\"col my-auto\"> <h6 class=\"mb-0\"> Jack Jacs</h6>  </div>\n");
      out.write("                                        <div class=\"col-auto my-auto\"> <small>Golden Rim </small></div>\n");
      out.write("                                        <div class=\"col my-auto\"> <small>Size : M</small></div>\n");
      out.write("                                        <div class=\"col my-auto\"> <small>Qty : 1</small></div>\n");
      out.write("                                        <div class=\"col my-auto\"><h6 class=\"mb-0\"> 360.00</h6>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <hr class=\"my-3 \">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-3 mb-3\"> <small> Track Order <span><i class=\" ml-2 fa fa-refresh\"  aria-hidden=\"true\"></i></span></small> </div>\n");
      out.write("                                <div class=\"col mt-auto\">\n");
      out.write("                                    <div class=\"progress my-auto\"> <div class=\"progress-bar progress-bar  rounded\" style=\"width: 62%\" role=\"progressbar\" aria-valuenow=\"25\" aria-valuemin=\"0\"  aria-valuemax=\"100\"></div> </div>\n");
      out.write("                                    <div class=\"media row justify-content-between \">\n");
      out.write("                                        <div class=\"col-auto text-right\"><span> <small  class=\"text-right mr-sm-2\"></small> <i class=\"fa fa-circle active\"></i> </span></div>\n");
      out.write("                                        <div class=\"flex-col\"> <span> <small class=\"text-right mr-sm-2\">Out for delivary</small><i class=\"fa fa-circle active\"></i></span></div>\n");
      out.write("                                        <div class=\"col-auto flex-col-auto\"><small  class=\"text-right mr-sm-2\">Delivered</small><span> <i  class=\"fa fa-circle\"></i></span></div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row mt-4\">\n");
      out.write("                <div class=\"col\">\n");
      out.write("                    <div class=\"card card-2\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <div class=\"media\">\n");
      out.write("                                <div class=\"sq align-self-center \"> <img class=\"img-fluid  my-auto align-self-center mr-2 mr-md-4 pl-0 p-0 m-0\" src=\"assets/images/Spectacles.jpeg\" width=\"135\" height=\"135\" /> </div>\n");
      out.write("                                <div class=\"media-body my-auto text-right\">\n");
      out.write("                                    <div class=\"row  my-auto flex-column flex-md-row\">\n");
      out.write("                                        <div class=\"col-auto my-auto \"> <h6 class=\"mb-0\"> Michel Mark</h6> </div>\n");
      out.write("                                        <div class=\"col my-auto  \"> <small>Black Rim </small></div>\n");
      out.write("                                        <div class=\"col my-auto  \"> <small>Size : L</small></div>\n");
      out.write("                                        <div class=\"col my-auto  \"> <small>Qty : 1</small></div>\n");
      out.write("                                        <div class=\"col my-auto \">  <h6 class=\"mb-0\"> 123.00</h6>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <hr class=\"my-3 \">\n");
      out.write("                            <div class=\"row \">\n");
      out.write("                                <div class=\"col-md-3 mb-3\">  <small> Track Order <span><i class=\" ml-2 fa fa-refresh\" aria-hidden=\"true\"></i></span></small> </div>\n");
      out.write("                                <div class=\"col mt-auto\">\n");
      out.write("                                    <div class=\"progress\"><div class=\"progress-bar progress-bar  rounded\" style=\"width: 18%\"  role=\"progressbar\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div> </div>\n");
      out.write("                                    <div class=\"media row justify-content-between \">\n");
      out.write("                                        <div class=\"col-auto text-right\"><span> <small  class=\"text-right mr-sm-2\"></small> <i class=\"fa fa-circle active\"></i> </span></div>\n");
      out.write("                                        <div class=\"flex-col\"> <span> <small class=\"text-right mr-sm-2\">Out for delivary</small><i class=\"fa fa-circle\"></i></span></div>\n");
      out.write("                                        <div class=\"col-auto flex-col-auto\"><smallclass=\"text-right mr-sm-2\">Delivered</small><span> <i class=\"fa fa-circle\"></i></span></div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row mt-4\">\n");
      out.write("                <div class=\"col\">\n");
      out.write("                    <div class=\"row justify-content-between\">\n");
      out.write("                        <div class=\"flex-sm-col text-right col\"> <p class=\"mb-1\"><b>Total</b></p> </div>\n");
      out.write("                        <div class=\"flex-sm-col col-auto\"> <p class=\"mb-1\"> 483</p> </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"row justify-content-between\">\n");
      out.write("                        <div class=\"flex-sm-col text-right col\"><p class=\"mb-1\"><b>Delivery Charges</b></p></div>\n");
      out.write("                        <div class=\"flex-sm-col col-auto\"><p class=\"mb-1\">Free</p></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row invoice \">\n");
      out.write("                <div class=\"col\"><p class=\"mb-1\"> Invoice Number : 788152</p><p class=\"mb-1\">Invoice Date : 22 Dec,2019</p></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-footer\">\n");
      out.write("            <div class=\"jumbotron-fluid\">\n");
      out.write("                <div class=\"row justify-content-between \">\n");
      out.write("                    <div class=\"col-sm-auto col-auto my-auto\"><img class=\"img-fluid my-auto align-self-center \" src=\"assets/images/favicon.ico\" width=\"115\" height=\"115\"></div>\n");
      out.write("                    <div class=\"col-auto my-auto \"><h2 class=\"mb-0 font-weight-bold\">TOTAL POINT</h2></div>\n");
      out.write("                    <div class=\"col-auto my-auto \"><h1 class=\"mb-1\"> 483</h1></div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row justify-content-between \">\n");
      out.write("                    <div class=\"flex-sm-col text-right col\"><p class=\"mb-1\"><b>Remaining Points</b></p></div>\n");
      out.write("                    <div class=\"flex-sm-col col-sm-auto\"><p class=\"mb-1\"><b>100</b></p></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-3 mt-3 mt-md-0\">\n");
      out.write("                    <div class=\"col-auto border-line\"> <small class=\"text-white\">PAN:AA02hDW7E</small></div>\n");
      out.write("                    <div class=\"col-auto border-line\"> <small class=\"text-white\">CIN:UMMC20PTC </small></div>\n");
      out.write("                    <div class=\"col-auto \"><small class=\"text-white\">GSTN:268FD07EXX </small> </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Ends -->\n");
      out.write("         </div>\n");
      out.write("     \n");
      out.write("        <!-- Page end  -->\n");
      out.write("    </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("\n");
      out.write("    <!-- Backend Bundle JavaScript -->\n");
      out.write("    <script src=\"assets/js/backend-bundle.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Table Treeview JavaScript -->\n");
      out.write("    <script src=\"assets/js/table-treeview.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Chart Custom JavaScript -->\n");
      out.write("    <script src=\"assets/js/customizer.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Chart Custom JavaScript -->\n");
      out.write("    <script async src=\"assets/js/chart-custom.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- app JavaScript -->\n");
      out.write("    <script src=\"assets/js/app.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
