/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-06-30 10:18:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class customer_002dcheckout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1719740939688L));
    _jspx_dependants.put("jar:file:/C:/Users/aqima/OneDrive/Desktop/myproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/REDEEM/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602845172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("    \n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("      <title>redeemMe</title>\n");
      out.write("      \n");
      out.write("      <!-- Favicon -->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/backend-plugin.min.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/backend.css?v=1.0.0\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/@fortawesome/fontawesome-free/css/all.min.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/vendor/remixicon/fonts/remixicon.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/customer-style.css\"> \n");
      out.write("     </head>\n");
      out.write("\n");
      out.write("      <!-- css -->\n");
      out.write("      <style>\n");
      out.write("        .las.la-bars.wrapper-menu:hover, .ri-menu-line.wrapper-menu:hover {\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn.border.sign-out{\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: medium;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn.border.sign-out:hover{\n");
      out.write("            background-color: #e32323;\n");
      out.write("            color: #ffffff;\n");
      out.write("            transition: all 0.7s ease-in-out;\n");
      out.write("        }\n");
      out.write("      </style>\n");
      out.write("\n");
      out.write("  <body class=\"  \">\n");
      out.write("    <!-- loader Start -->\n");
      out.write("    <div id=\"loading\">\n");
      out.write("          <div id=\"loading-center\">\n");
      out.write("          </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- loader END -->\n");
      out.write("    <!-- Wrapper Start -->\n");
      out.write("    <div class=\"wrapper\">\n");
      out.write("      \n");
      out.write("      <div class=\"iq-sidebar  sidebar-default \">\n");
      out.write("          <div class=\"iq-sidebar-logo d-flex align-items-center justify-content-between\">\n");
      out.write("              <a href=\"customer-shop.jsp\" class=\"header-logo\">\n");
      out.write("                  <img src=\"assets/images/logo.png\" class=\"img-fluid rounded-normal light-logo\" alt=\"logo\"><h5 class=\"logo-title light-logo ml-3\">redeemMe</h5>\n");
      out.write("              </a>\n");
      out.write("              <div class=\"iq-menu-bt-sidebar ml-0\">\n");
      out.write("                  <i class=\"las la-bars wrapper-menu\"></i>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"data-scrollbar\" data-scroll=\"1\">\n");
      out.write("            <nav class=\"iq-sidebar-menu\">\n");
      out.write("                <ul id=\"iq-sidebar-toggle\" class=\"iq-menu\">\n");
      out.write("                    <li class=\"active\">\n");
      out.write("                        <a href=\"customer-profile.jsp\" class=\"svg-icon\">                        \n");
      out.write("                          <svg class=\"svg-icon\" id=\"p-dash8\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n");
      out.write("                              <path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path><circle cx=\"9\" cy=\"7\" r=\"4\"></circle><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path>\n");
      out.write("                          </svg>\n");
      out.write("                            <span class=\"ml-4\">Profile</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\" \">\n");
      out.write("                        <a href=\"ListProductControllerCustomer\">\n");
      out.write("                          <svg class=\"svg-icon\" id=\"p-dash2\" width=\"20\" height=\"20\"  xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"9\" cy=\"21\" r=\"1\"></circle><circle cx=\"20\" cy=\"21\" r=\"1\"></circle>\n");
      out.write("                              <path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path>\n");
      out.write("                          </svg>\n");
      out.write("                            <span class=\"ml-4\">Shop</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\" \">\n");
      out.write("                      <a href=\"customer-purchases.jsp\">\n");
      out.write("                          <svg class=\"svg-icon\" id=\"p-dash5\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"1\" y=\"4\" width=\"22\" height=\"16\" rx=\"2\" ry=\"2\"></rect>\n");
      out.write("                              <line x1=\"1\" y1=\"10\" x2=\"23\" y2=\"10\"></line>\n");
      out.write("                          </svg>\n");
      out.write("                          <span class=\"ml-4\">Purchases</span>\n");
      out.write("                      </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("            <div id=\"sidebar-bottom\" class=\"position-relative sidebar-bottom\"></div>\n");
      out.write("        </div>\n");
      out.write("          </div>      <div class=\"iq-top-navbar\">\n");
      out.write("          <div class=\"iq-navbar-custom\">\n");
      out.write("              <nav class=\"navbar navbar-expand-lg navbar-light p-0\">\n");
      out.write("                  <div class=\"iq-navbar-logo d-flex align-items-center justify-content-between\">\n");
      out.write("                      <i class=\"ri-menu-line wrapper-menu\"></i>\n");
      out.write("                      <a href=\"customer-shop.jsp\" class=\"header-logo\">\n");
      out.write("                          <img src=\"assets/images/logo.png\" class=\"img-fluid rounded-normal\" alt=\"logo\">\n");
      out.write("                          <h5 class=\"logo-title ml-3\">redeemMe</h5>\n");
      out.write("                      </a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"current-points\">\n");
      out.write("                    Your Points: ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(" &#9733;\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"d-flex align-items-center\">\n");
      out.write("                      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("                          data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\n");
      out.write("                          aria-label=\"Toggle navigation\">\n");
      out.write("                          <i class=\"ri-menu-3-line\"></i>\n");
      out.write("                      </button>\n");
      out.write("                      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                          <ul class=\"navbar-nav ml-auto navbar-list align-items-center\">\n");
      out.write("                              <li class=\"nav-item nav-icon dropdown\" style=\"display: flex; align-self: end;\">\n");
      out.write("                                  <p>Hi, <span style=\"color: red;\">");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</span></p>\n");
      out.write("                              </li>\n");
      out.write("                              <li class=\"nav-item nav-icon dropdown caption-content\">\n");
      out.write("                                  <a href=\"#\" class=\"search-toggle dropdown-toggle\" id=\"dropdownMenuButton4\"\n");
      out.write("                                      data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                      <img src=\"assets/images/user/1.png\" class=\"img-fluid rounded\" alt=\"user\">\n");
      out.write("                                  </a>\n");
      out.write("                                  <div class=\"iq-sub-dropdown dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\n");
      out.write("                                      <div class=\"card shadow-none m-0\">\n");
      out.write("                                          <div class=\"card-body p-0 text-center\">\n");
      out.write("                                              <div class=\"media-body profile-detail text-center\">\n");
      out.write("                                                  <img src=\"assets/images/page-img/profile-bg.jpg\" alt=\"profile-bg\"\n");
      out.write("                                                      class=\"rounded-top img-fluid mb-4\">\n");
      out.write("                                                  <img src=\"assets/images/user/1.png\" alt=\"profile-img\"\n");
      out.write("                                                      class=\"rounded profile-img img-fluid avatar-70\">\n");
      out.write("                                              </div>\n");
      out.write("                                              <div class=\"p-3\">\n");
      out.write("                                                  <p class=\"mb-0\">customer email</p>\n");
      out.write("                                                  <div class=\"d-flex align-items-center justify-content-center mt-3\">\n");
      out.write("                                                      <a href=\"login.jsp\" class=\"btn border sign-out\">Sign Out</a>\n");
      out.write("                                                  </div>\n");
      out.write("                                              </div>\n");
      out.write("                                          </div>\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                              </li>\n");
      out.write("                          </ul>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("              </nav>\n");
      out.write("          </div>\n");
      out.write("      </div>    <div class=\"content-page\">\n");
      out.write("<!-- Starts here -->\n");
      out.write("   \n");
      out.write("	<div class=\"container\">\n");
      out.write("        <div class=\"checkoutLayout\">\n");
      out.write("            <div class=\"left\">\n");
      out.write("			<form action=\"CheckOutCustomerController?productId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"Post\">\n");
      out.write("			    <h1>List Product</h1>\n");
      out.write("			    <div class=\"form\">\n");
      out.write("			        <div class=\"group\">\n");
      out.write("			            <div class=\"input-field\">\n");
      out.write("			                <label for=\"Id\">Product Id</label>\n");
      out.write("			                <input type=\"text\" name=\"productId\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("			            </div>\n");
      out.write("			        </div>\n");
      out.write("			        <div class=\"group\">\n");
      out.write("			            <label for=\"Name\">Product Name</label>\n");
      out.write("			            <input type=\"text\" name=\"Name\" id=\"productName\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("			        </div>\n");
      out.write("			        <div class=\"group\">\n");
      out.write("			            <label for=\"Category\">Product Category</label>\n");
      out.write("			            <input type=\"text\" name=\"category\" id=\"productCategory\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productCategory}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("			        </div>\n");
      out.write("			        <div class=\"group\">\n");
      out.write("			            <label for=\"description\">Product Description</label>\n");
      out.write("			            <input type=\"text\" name=\"description\" id=\"productDescription\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productDescription}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("			        </div>\n");
      out.write("			    </div>\n");
      out.write("			</form>\n");
      out.write("            </div>\n");
      out.write("                	\n");
      out.write("        <div class=\"right\">\n");
      out.write("        <form action=\"CheckOutCustomerController?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"POST\">\n");
      out.write("            <div class=\"form\">\n");
      out.write("            <h1>Receiver Details</h1>\n");
      out.write("\n");
      out.write("                <div class=\"group\">\n");
      out.write("		             <div class=\"input-field\">\n");
      out.write("		                    <label>Full Name</label>\n");
      out.write("		                     <input type=\"text\" name=\"firstName\" class=\"form-control\"  value=\"");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("		              </div>\n");
      out.write("		    \n");
      out.write("		              <div class=\"group\">\n");
      out.write("		                <label for=\"phone\">Phone Number</label>\n");
      out.write("		                <input type=\"text\" name=\"phone\" id=\"mobile\" value=\"");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("		              </div>\n");
      out.write("		\n");
      out.write("		              <div class=\"group\">\n");
      out.write("		                <label for=\"address\">Address</label>\n");
      out.write("		                <input type=\"text\" name=\"address\" id=\"address1\" value=\"");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("		              </div>\n");
      out.write("            	</div>\n");
      out.write("            	\n");
      out.write("                    <div class=\"total-points-container\" style=\"display: flex; justify-content: space-between; align-items: center; font-size: 2em; font-weight: bold;\">\n");
      out.write("					  	<div>Total points</div>\n");
      out.write("					    <div class=\"totalpoints\">");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("					</div>\n");
      out.write("          \n");
      out.write("    		</div>\n");
      out.write("    <a class=\"buttonCheckout\" style=\"justify-self: center;\" href = \"customer-receipt.jsp\">CHECKOUT</a>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("<!-- Ends -->\n");
      out.write("         </div>\n");
      out.write("     \n");
      out.write("        <!-- Page end  -->\n");
      out.write("    </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Wrapper End-->\n");
      out.write("    <footer class=\"iq-footer\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-body\" style=\"text-align: center;\">\n");
      out.write("                    <span class=\"mr-1\"><script>document.write(new Date().getFullYear())</script>Â©</span> <a href=\"customer-shop.jsp\" class=\"\">redeemMe</a>.\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script src=\"assets/js/customer-checkout.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Backend Bundle JavaScript -->\n");
      out.write("    <script src=\"assets/js/backend-bundle.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Table Treeview JavaScript -->\n");
      out.write("    <script src=\"assets/js/table-treeview.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Chart Custom JavaScript -->\n");
      out.write("    <script src=\"assets/js/customizer.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Chart Custom JavaScript -->\n");
      out.write("    <script async src=\"assets/js/chart-custom.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- app JavaScript -->\n");
      out.write("    <script src=\"assets/js/app.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /customer-checkout.jsp(101,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.points}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /customer-checkout.jsp(112,67) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /customer-checkout.jsp(182,88) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName} ${user.lastName}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /customer-checkout.jsp(187,69) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.mobile}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /customer-checkout.jsp(192,73) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.address1}, ${user.address2}, ${user.postcode}, ${user.city}, ${user.state}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /customer-checkout.jsp(198,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productPoints}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }
}
